### ISSUE TITLE
Couldn't find GetBatteryState function

### ISSUE THREAD

**Issue by blairysecle2** [And3rsL/Deebot-for-hassio#1]
Hi,

I enjoyed reading your work and would like to check if my Ozmo 920 could also be supported by your fork.

I installed your library with a 
pip3 install deebotozmo
pip3 install sucks
and everything worked fine.

I successfully logged in by using python3 cli.py login

Now when trying to call  python3 cli.py --debug batterystate
i'm getting
Traceback (most recent call last):
  File "cli.py", line 271, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1086, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 216, in batterystate
    return CliAction(GetBatteryState(), terminal=False)
NameError: name 'GetBatteryState' is not defined

It seems that the GetBatteryState function is not found (probably defined in sucks library).

Could you please help me to get it running?

Many thanks in advance.
Blairy

**Comment by And3rsL** [comment]
You don't need to install sucks library, this library should be used with hassio add-on.

Cli.py is not maintened and I used it just for debbugging

**Comment by blairysecle2** [comment]
Hi,
thank you for answering. OK sorry I thought I could use it directly with a Python call.
No problem I will wait for your next push.
Thanks.

**Comment by And3rsL** [comment]
try now "py cli.py --debug batterystate" it should work
