### ISSUE TITLE
 I need help DEEBOT OZMO 930 

### ISSUE THREAD

**Issue by valy2000** [And3rsL/Deebot-for-hassio#12]
2020-04-05 10:17:53 ERROR (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-04-05 10:17:53 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2020-04-05 10:17:54 ERROR (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-04-05 10:17:54 ERROR (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-04-05 10:17:54 ERROR (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-04-05 10:17:54 ERROR (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-04-05 10:17:55 ERROR (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-04-05 10:17:55 ERROR (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-04-05 10:17:55 ERROR (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-04-05 10:17:56 ERROR (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-04-05 10:17:56 WARNING (MainThread) [homeassistant.setup] Setup of updater is taking over 10 seconds.
2020-04-05 10:17:57 ERROR (MainThread) [homeassistant.components.vacuum] deebot: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    await self.async_update()
  File "/config/custom_components/deebot/vacuum.py", line 224, in async_update
    await self.hass.async_add_executor_job(self.device.request_all_statuses)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 651, in request_all_statuses
    self.refresh_components()
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 630, in refresh_components
    self.exc_command('GetCleanLogs')
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 701, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 705, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 807, in send_command
    self._handle_ctl_api(action, self.__call_logs_api(c ,verify_ssl=self.verify_ssl ))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 928, in _handle_ctl_api
    s(resp)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 453, in _handle_ctl
    getattr(self, method)(ctl)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 501, in _handle_clean_logs
    self.last_clean_image = response[0]['imageUrl']
IndexError: list index out of range
2020-04-05 10:18:20 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform alexa_media is taking over 10 seconds.
2020-04-05 10:18:20 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform alexa_media is taking over 10 seconds.
2020-04-05 10:19:34 ERROR (MainThread) [frontend.js.latest.202003181] :0:0 Script error.

**Comment by And3rsL** [comment]
Sorry but this custom_component doesnt support deebot ozmo 930

**Comment by nicecube** [comment]
Hi, could you make it work with 930, was thinking it was working bc its the same serie,

**Comment by And3rsL** [comment]
sorry but ecovacs API are completely different for 930.. no support here

Try Ligio custom component, it should work
https://github.com/Ligio/hacc-ozmo
