### ISSUE TITLE
[HA Core 0.109.x] Detected I/O inside the event loop

### ISSUE THREAD

**Issue by elmurato** [And3rsL/Deebot-for-hassio#15]
Hi @And3rsL,

First of all thanks for this custom integration. I was not so happy to see that my OZMO 950 is not yet supported by the sucks library. Then I saw this custom integration and it's running perfect. Thanks so much!

After upgrading to Home Assistant Core 0.109.x the new feature which automatically detects blocking I/O in the event loop found something in your integration. Could you have a look at it? Thanks in advance. 

Here is the logger output from HA:

> Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for deebot doing I/O at custom_components/deebot/vacuum.py, line 93: config.get(CONF_CONTINENT),
> Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for deebot doing I/O at custom_components/deebot/vacuum.py, line 97: devices = ecovacs_api.devices()

**Comment by StefanoGiu** [comment]
Same issue for me:

`2020-05-11 10:09:56 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up deebot platform for vacuum
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "C:\Python38\lib\asyncio\tasks.py", line 483, in wait_for
    return fut.result()
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\deebot\vacuum.py", line 88, in async_setup_platform
    ecovacs_api = EcoVacsAPI(
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 200, in __init__
    login_info = self.__call_main_api('user/login',
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 234, in __call_main_api
    api_response = requests.get(url, self.__sign(params), verify=self.verify_ssl)
  File "C:\Python38\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1241, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\urllib3\connection.py", line 199, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "C:\Python38\lib\site-packages\homeassistant\util\async_.py", line 120, in protected_loop_func
    check_loop()
  File "C:\Python38\lib\site-packages\homeassistant\util\async_.py", line 91, in check_loop
    raise RuntimeError(
RuntimeError: Detected I/O inside the event loop. This is causing stability issues. Please report issue
`

**Comment by And3rsL** [comment]
Im currently working on live map support, i will fix it asap :)

**Comment by StefanoGiu** [comment]
Great news!!! Well done @And3rsL . Will the live map support fix also fix the latest clean image, that is not the very last one?

**Comment by markmghali** [comment]
I am also seeing this in the log. But looks like you are on it!

Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 8:56:22 AM (4 occurrences)
Last logged: 8:56:23 AM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for deebot doing I/O at custom_components/deebot/vacuum.py, line 93: config.get(CONF_CONTINENT),
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for deebot doing I/O at custom_components/deebot/vacuum.py, line 97: devices = ecovacs_api.devices()

**Comment by kebel87** [comment]
> Im currently working on live map support, i will fix it asap :)

Will it fix the error we are getting with the HACS integration for Deebot 950? Thanks!

I have the same I/O loop error as others.

Thanks!

**Comment by And3rsL** [comment]
Should be fixed now

**Comment by kebel87** [comment]
Hi @And3rsL ,

I updated the integration and got this error after restarting HA. 

Log Details (ERROR)
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:277 
Integration: Hass.io (documentation, issues) 
First occurred: 12:45:28 PM (1 occurrences) 
Last logged: 12:45:28 PM

Invalid config for [vacuum.deebot]: required key not provided @ data['livemappath']. Got None. (See ?, line ?).

My confie is : 

vacuum:
  - platform: deebot
    username: email@hotmail.com
    password: myPassWord
    country: ca
    continent: na
    deviceid: E000....

**Comment by kebel87** [comment]
Oh, I figured we must add a new line in the config. Lemme try again and get back to you.

**Comment by StefanoGiu** [comment]
@kebel87  read the readme file :)

**Comment by elmurato** [comment]
Fixed with version 1.7. Good work @And3rsL !
