### ISSUE TITLE
 No such file or directory: 'www/live_map.png'`

### ISSUE THREAD

**Issue by StefanoGiu** [And3rsL/Deebot-for-hassio#18]
`2020-05-19 18:29:16 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 550, in _update_entity_states
    await asyncio.gather(*tasks)
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity.py", line 324, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\deebot\vacuum.py", line 268, in device_state_attributes
    with open(LIVE_MAP_PATH, "wb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'www/live_map.png'`

**Comment by And3rsL** [comment]
Create folder 'www' insider config directory

**Comment by StefanoGiu** [comment]
I already have the folder www ;)

**Comment by StefanoGiu** [comment]
Ontop of this, it doesn't seem to read the path from the cfg file...

I tried both:
livemappath: 'local/live_map.png'
and
livemappath: 'www/live_map.png'

But the error in both cases is:
[Errno 2] No such file or directory: 'www/live_map.png'

**Comment by And3rsL** [comment]
Is It Windows installation? Can tour try www\ ?

**Comment by StefanoGiu** [comment]
Yes Windows... I tried it...

Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 550, in _update_entity_states
    await asyncio.gather(*tasks)
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity.py", line 324, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\deebot\vacuum.py", line 268, in device_state_attributes
    with open(LIVE_MAP_PATH, "wb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'www\\live_map.png'

**Comment by StefanoGiu** [comment]
Please also consider that the filename is not read from the config file... it always take what's written as default in vacuum.py...

**Comment by And3rsL** [comment]
filename should be read from the config now

**Comment by StefanoGiu** [comment]
Still not working...

`2020-05-19 22:50:20 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity_platform.py", line 550, in _update_entity_states
    await asyncio.gather(*tasks)
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity.py", line 324, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\deebot\vacuum.py", line 278, in device_state_attributes
    with open(self._live_map_path, "wb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'www/live_map.png'
`

**Comment by And3rsL** [comment]
Maybe full Path?

`C:\Users\stefa\AppData\Roaming\.homeassistant\config\www\live_map.png`

**Comment by StefanoGiu** [comment]
With full path it works... I need to use "/" and not "\". Is it possible to have the relative path working?

**Comment by And3rsL** [comment]
> With full path it works... I need to use "/" and not "". Is it possible to have the relative path working?

it depends by home assistant, can't do anything about that sorry

i will add this solution in the readme file 👍

**Comment by StefanoGiu** [comment]
Hello,

I just tested the live map, but I'm not getting the use of it, maybe I'm wrong.

On HA I see...
![image](https://user-images.githubusercontent.com/35804888/82422384-a7cedf00-9a82-11ea-9804-170401bc30d5.png)

While on the app I see...
![Screenshot_20200520-100939_ECOVACS HOME](https://user-images.githubusercontent.com/35804888/82422465-c6cd7100-9a82-11ea-8dfc-8dc15f056ae6.jpg)


Should the live map display the white line that shows the path of the deebot? Why I cannot see the room division?

**Comment by And3rsL** [comment]
Now there is support for robot,charge and room colors! no display path avaiable for now
