### ISSUE TITLE
Errors when initializing 930

### ISSUE THREAD

**Issue by guice** [And3rsL/Deebot-for-hassio#2]
I did a fresh pull and copied over the deebot directory, 
```
➜  custom_components cp -R deebot.repo/custom_components/deebot . 
➜  custom_components ls deebot 
__init__.py* __pycache__/ vacuum.py*
````

The errors from the log (filtered to just the deebot errors)

```
2020-01-30 10:52:18 ERROR (MainThread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
2020-01-30 10:52:20 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up platform deebot
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 796, in shield
    inner = ensure_future(arg, loop=loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 619, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
2020-01-30 10:52:20 ERROR (MainThread) [custom_components.deebot.vacuum] STATE not supported: None
```

I do have the follow logger settings, but they don't seem to be working. I assumed this component is named `deebot`:
```yaml
deebot:
  username: !secret email
  password: !secret ecovac_password
  country: us
  continent: na

logger:
  logs:
    homeassistant.components.deebot: debug
    homeassistant.components.vacuum.deebot: debug
    sucks: debug
```

**Comment by guice** [comment]
This continues to repeat over and over:
```
call to iotdevmanager failed with {'ret': 'fail', 'errno': 3002}
```

**Comment by And3rsL** [comment]
entity doesnt appear?

I think its because ozmo 930 is XML based, does it work with https://github.com/Ligio/hacc-ozmo?

**Comment by guice** [comment]
Yeah. That one is working. And I can even control it, start, return to home, etc.

**Comment by And3rsL** [comment]
ecovacs keep changing its API so i think this repos is ozmo 950 specific (or maybe next models?)

definitively not compatible with 930 sorry

**Comment by guice** [comment]
No worries. I get it. Thought I'd try. This could be an incoming firmware - moving from XML => JSON does make sense. I'm rather surprised that their different 9xx vacuums are using different firmware.
