### ISSUE TITLE
1.9.0 causes 100% CPU usage.

### ISSUE THREAD

**Issue by danielbahl** [And3rsL/Deebot-for-hassio#23]
Last update (1.9.0) seems to cause my Home Assistant to eat 100% CPU 🥵 

I thought it might just be in the beginning, after the update and a reboot, but it has running for the last 4-5 hours, and are still eating 100+% CPU. I've tried to restart but it continues. The img-file is never generated in the www-folder.

If I disable the addon in configuration.yaml, CPU usage is normal (5-10% load). 

I've tried booting with debug log enabled and let it run for about 5 minutes, then I had to restart again without the plugin as HASS was useless in that state 😅 .. and the whole family are home now, so we need our Home Assistant 😄 .. I can debug furhter tomorrow if you need more logs..

![CleanShot 2020-05-27 at 20 56 39](https://user-images.githubusercontent.com/628182/83065935-9b3f1d80-a064-11ea-8ab8-d2296351664e.png)

![CleanShot 2020-05-27 at 16 34 12](https://user-images.githubusercontent.com/628182/83066070-c9246200-a064-11ea-875b-8f29a138aa66.png)

![CleanShot 2020-05-27 at 15 46 46 kopi](https://user-images.githubusercontent.com/628182/83066361-3d5f0580-a065-11ea-93fc-5f0f2e20ccea.png)

Home Assistant 0.110.3
HassOS 3.13

**Complete log-file dump** attached here: 
[deebot-And3rsL.log](https://github.com/And3rsL/Deebot-for-hassio/files/4691474/deebot-And3rsL.log)

```
2020-05-27 21:29:07 ERROR (schedule_thread_livemap) [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/thread.py", line 20, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 484, in refresh_liveMap
    self.live_map = self.__map.GetBase64Map()
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/map.py", line 228, in GetBase64Map
    im = im.resize((im.size[0]*resizeFactor, im.size[1]*resizeFactor), Image.NEAREST)
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 1883, in resize
    im = im.resize(size, resample, box)
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 1905, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: image has wrong mode

```

**Comment by And3rsL** [comment]
Thanks for the detailed report!

From a first check I can see that your map is rendered over the 3000pixel limit I set. It can cause the error, tomorrow I will release a fix and see if it can fix your problem

Maybe related to https://github.com/And3rsL/Deebot-for-hassio/issues/22#issue-625665998

**Comment by danielbahl** [comment]
Thank you! Let me know if I can help with anything debugging / testing related. And thank you for your awesome plugin and the work you've put into making our Robot vacuum suck even better with Home Assistant 😍  😉  I'm going to write about it on my danish Home Automation blog [Robotnet.dk](https://robotnet.dk) in the coming weeks 😄

**Comment by And3rsL** [comment]
> Thank you! Let me know if I can help with anything debugging / testing related. And thank you for your awesome plugin and the work you've put into making our Robot vacuum suck even better with Home Assistant 😍 😉 I'm going to write about it on my danish Home Automation blog [Robotnet.dk](https://robotnet.dk) in the coming weeks 😄

Thank you 😃 
Please test the new release and let me know if its working 👍

**Comment by anup92k** [comment]
Hello,
I might have the same issue with :
Home Assistant : 0.110.4
Ubuntu 18.04 LTS (HA is installed in a python venv with pip)
Plugin version : 1.9.1
Vaccum : Ozmo 920

```yaml
# FILE : configuration.yaml
vacuum: !include vacuums.yaml
````

```yaml
# FILE : vacuums.yaml
# HACS "Deebot 960/950/920 vacuum"
# https://github.com/And3rsL/Deebot-for-hassio
- platform: deebot
  username: !secret secret_evocacs_username
  password: !secret secret_evocacs_password
  country: fr
  continent: eu
  deviceid: !secret debbot_920_sn
  livemappath: 'www/live_map.png'
````
![ha_deebotintegration_cpu](https://user-images.githubusercontent.com/51033013/83310239-a5e7e700-a20b-11ea-9cce-609a5bb9a8cc.png)

I'll re-add this integration tomorrow with the debug option of HA to see what's going on.

If it's maybe related to the `livemappath` can I try removing it or it will cause issues ?

_BTW this is the first integration that was able to find my vacuum ! Thx for your work on this !_

**Comment by anup92k** [comment]
Hello,

So I've done some tests.


Cleaning from 14h52 to 15h26
Apply deebot config (restart HA) : aproximatively at ~15h15
Remove deebot config (restart HA): 15h39

![Screenshot_1](https://user-images.githubusercontent.com/51033013/83356773-8c0fe680-a368-11ea-8ca5-da585d165fc9.png)
![Screenshot_2](https://user-images.githubusercontent.com/51033013/83356777-90d49a80-a368-11ea-83de-4b665ca808fd.png)

The related log file : [home-assistant_deebot.log](https://github.com/And3rsL/Deebot-for-hassio/files/4707919/home-assistant_deebot.log)

I've tried re-applied the config and just restart HA when the CPU is overloaded.
If you restart HA the CPU goes down.
In those tests, the vacuum was just charging at his base.
**The CPU get overload about 20min after every restart I've done.**

I've been tailing the log to see what cause it and this is the relative part :
```
tail -f home-assistant.log | grep -e deebot -e vacuum -e ozmo
[...]
2020-05-31 17:39:28 DEBUG (schedule_thread_statuses) [deebotozmo] [refresh_statuses] Begin
2020-05-31 17:39:28 DEBUG (schedule_thread_components) [deebotozmo] [refresh_components] Begin
2020-05-31 17:39:49 DEBUG (schedule_thread_statuses) [deebotozmo] [refresh_statuses] Begin
2020-05-31 17:39:49 DEBUG (schedule_thread_components) [deebotozmo] [refresh_components] Begin
2020-05-31 17:40:01 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Draw room: 7
2020-05-31 17:40:01 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Draw room: 8
2020-05-31 17:40:01 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Draw room: 9
2020-05-31 17:40:02 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Draw Map
2020-05-31 17:40:10 DEBUG (schedule_thread_statuses) [deebotozmo] [refresh_statuses] Begin
2020-05-31 17:40:10 DEBUG (schedule_thread_components) [deebotozmo] [refresh_components] Begin
2020-05-31 17:40:12 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Draw Trace
2020-05-31 17:40:12 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Draw robot
2020-05-31 17:40:12 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Draw charge station
2020-05-31 17:40:12 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Flipping Image
2020-05-31 17:40:12 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Crop Image
2020-05-31 17:40:13 DEBUG (schedule_thread_livemap) [deebotozmo.map] [GetBase64Map] Resize * 3
```

It seams that the `GetBase64Map` is doing the issue because my SSH connexion slowed down since.

You can see bellow my monitoring events.
_I send a "Home Assistant <version> est prêt !" when HA start.
The other notifications came from Nagios.
Read the notifications like Twitter : older from bottom_
![Screenshot_3](https://user-images.githubusercontent.com/51033013/83356823-d85b2680-a368-11ea-82d9-b129743ed166.png)

My server is a very cheep thing :
- Intel Atom x5*Z8350
- 2GB of RAM

At normal usage the CPU is about 15% and 50% for the RAM.
Maybe it's because of that.

I tried remove the `livemappath` ine the config but it trow and error.
Maybe if this feature could be optionnal it will work with low computers like mine.

If you attend to work on this, if there is anything I can do to help you I will be happy to help.

**Comment by anup92k** [comment]
Hello,
Many thanks for your work on release 1.9.2 ! 🥇 
I've added `live_map: False` and since, no CPU issues.
Thanks a lot for this component. I've been looking for something functional for months and you've done it !

For my part, this issue can be closed for me 👍
