### ISSUE TITLE
Upgrading to latest version

### ISSUE THREAD

**Issue by markmghali** [And3rsL/Deebot-for-hassio#25]
I am now seeing this issue I am on 1.9.1
Deebot ozmo 950

Logger: root
Source: util/thread.py:20
First occurred: 8:08:32 AM (3 occurrences)
Last logged: 8:08:43 AM

Uncaught exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/thread.py", line 20, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 483, in refresh_liveMap
    self.exc_command('getMapTrace',{'pointCount':200,'traceStart':0})
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 573, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 577, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/ecovacsiotmq.py", line 115, in send_command
    self._handle_ctl_api(action, self.CallIOTApi(self.jsonRequestHeader(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/ecovacsiotmq.py", line 208, in _handle_ctl_api
    s(resp)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 255, in _handle_ctl
    getattr(self, method)(ctl)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 339, in _handle_map_trace
    self.__map.updateTracePoints(response['traceValue'])
KeyError: 'traceValue'###

**Comment by markmghali** [comment]
I tried re-installing the integration and it seemed to clear it up
