### ISSUE TITLE
1.9.1 generates a lot of uncaught exception errors

### ISSUE THREAD

**Issue by hanlongwang** [And3rsL/Deebot-for-hassio#26]
2020-05-30 00:53:26 ERROR (schedule_thread_livemap) [root] Uncaught exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/thread.py", line 20, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 483, in refresh_liveMap
    self.exc_command('getMapTrace',{'pointCount':200,'traceStart':0})
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 573, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 577, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/ecovacsiotmq.py", line 115, in send_command
    self._handle_ctl_api(action, self.CallIOTApi(self.jsonRequestHeader(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/ecovacsiotmq.py", line 208, in _handle_ctl_api
    s(resp)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 255, in _handle_ctl
    getattr(self, method)(ctl)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 339, in _handle_map_trace
    self.__map.updateTracePoints(response['traceValue'])

**Comment by scottyphillips** [comment]
Here is another one for (v1.9.2)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/thread.py", line 20, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 466, in refresh_components
    self.exc_command('GetCleanLogs')
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 582, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 586, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/ecovacsiotmq.py", line 113, in send_command
    self._handle_ctl_api(action, self.CallCleanLogsApi(self.jsonRequestHeaderCleanLogs(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/ecovacsiotmq.py", line 212, in _handle_ctl_api
    s(resp)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 259, in _handle_ctl
    getattr(self, method)(ctl)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 303, in _handle_clean_logs
    self.last_clean_image = response[0]['imageUrl']
IndexError: list index out of range

This is for Deebot 600. This model doesn't really do the whole mapping thing...
