### ISSUE TITLE
deebot 950 not working.

### ISSUE THREAD

**Issue by Vorms** [And3rsL/Deebot-for-hassio#27]
Hello, dump of error:
Détails du journal ( ERROR )
Logger: root
Source: util/thread.py:20
First occurred: 13:02:00 (1059 occurrences)
Last logged: 19:11:59

Uncaught exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/thread.py", line 20, in run
    run_old(*args, **kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 460, in refresh_components
    self.exc_command('GetCleanLogs')
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 573, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 577, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/ecovacsiotmq.py", line 113, in send_command
    self._handle_ctl_api(action, self.CallCleanLogsApi(self.jsonRequestHeaderCleanLogs(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/ecovacsiotmq.py", line 208, in _handle_ctl_api
    s(resp)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 255, in _handle_ctl
    getattr(self, method)(ctl)
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 299, in _handle_clean_logs
    self.last_clean_image = response[0]['imageUrl']
IndexError: list index out of range

Many thanks for your help !

**Comment by Vorms** [comment]
With the latest version it's run !
How can I start the vacum cleaner in an automation ?
Regards
