### ISSUE TITLE
Exception when no cleaning map was found - First installation

### ISSUE THREAD

**Issue by StefanoGiu** [And3rsL/Deebot-for-hassio#28]
Exception in thread schedule_thread_components:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 466, in refresh_components
    self.exc_command('GetCleanLogs')
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 582, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 586, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\ecovacsiotmq.py", line 113, in send_command
    self._handle_ctl_api(action, self.CallCleanLogsApi(self.jsonRequestHeaderCleanLogs(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\ecovacsiotmq.py", line 223, in _handle_ctl_api
    s(resp)
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 259, in _handle_ctl
    getattr(self, method)(ctl)
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 303, in _handle_clean_logs
    self.last_clean_image = response[0]['imageUrl']
IndexError: list index out of range

**Comment by StefanoGiu** [comment]
I fixed it in this way:
if response != None and len(response) > 0 and 'imageUrl' in response[0]:

I think that you want to check if it has at least one element (so >0 and not >=0).

Still I cannot see the vacuum working (but no error in the logs).
