### ISSUE TITLE
Running both Ecovacs and deebot component

### ISSUE THREAD

**Issue by h4nc** [And3rsL/Deebot-for-hassio#3]
Coming from [here](https://community.home-assistant.io/t/fixed-ecovacs-deebot-2019-ozmo-series-working-library/126319/111?u=h4nc).

I habe two ecovacs vacuum cleaners. A deebot slim2, which works fine with the ecovacs component and the new OZMO 950, which doesn't work with the ecovacs component, which is why I installed this component here. 

I'm facing issues with running both components. The reason why I don't run the deebot component only is that the slim2 get's unavailable with this component. 

So what I'm trying to do is using ecovacs for the slim2 and deebot for the OZMO 950. 
The thing is after adding deebot to my config my home assistant isn't able to restart reliable any more. I checked the config and no errors. So after that I need to comment out one of both components and ssh into my ha to restart my system. 
It started fine once, so both components were running but only the deebot component worked. 

There is only one suspicious Error in ha logs, all other log entires are related to other components (Info).
`ERROR (read_thread) [sleekxmppfs.xmlstream.xmlstream] Error reading from XML stream.`

I'd like to point out again, that it works if I only use one of both components.

**Comment by And3rsL** [comment]
Do you use same credentials (and maybe same app?) to controlling both devices?

**Comment by h4nc** [comment]
Yes, same account for both. 

The Ozmo got a new app, but with our doing anything the Slim2 showed up in the new app too, because they are linked to the same account.

**Comment by h4nc** [comment]
I'm facing another (maybe related) issue. Now even when I uncommented the ecovacs component, my ha isn't able to restart (although no error in the config check). Had to comment out deebot to be able to start it again.

**Comment by h4nc** [comment]
I ran in an even bigger issue. My frontend doesn't load any more. The thing is I already had this issue once this week but I thought it was because of the 0.105 update and the new netatmo changes. 
So i restored a backup which ran fine that last two days.

I added back the deebot component and now after trying to restart my system seems to be broken again. Even rebooting hassio doesn't work. That's bad.

**Comment by And3rsL** [comment]
It's very unlikely that a component can break hassio frontend, anyway I will investigate to check if there is anything. 

I will also insert a check for not setup older robots Maybe it can resolve your issue :D

Can you check if without deebot components your instance reebot fine multiple times? (I'm thinking maybe sd card corrupt?) 

Will try my best!

**Comment by h4nc** [comment]
I would also say that it is unlikely, but the thing is it happened the second time this week, both times a few hours after installing the component.

Deleting the component after the error did not help.

Currently I’m restoring a backup from some hours before the installation. I think if it works fine again after restoring the backup, than it’s probably not a corrupted as card?

**Comment by h4nc** [comment]
With the restored backup (before adding the component) HA core (formally known as HA) and ha (formally hassio) restart/reboot fine.

**Comment by h4nc** [comment]
Ok, so it ran fine for the last two days without the component. Some hours ago I reinstalled the deebot component, with several restarts and no issues. However I uncommented the ecovacs component, as I have the feeling that the issue is caused by running both components with the same account. I have no proof for that, just a feeling. 

Would you mean that running both components with the same account could cause issues? Could you also try it?
What I'm planning to do is to let the system run for the next days, to see if the issue reappears. If not I will probably try to re-add the ecovacs component.

Are you planning to adding the capabilities (ozmo950) of this component to the ecovacs or should this stay it's own component.

**Comment by And3rsL** [comment]
Hi,
You should be able to filter only devices you want from the new config "deviceid" section

please check it and let me know

**Comment by h4nc** [comment]
> the new config "deviceid" section

Do you mean in the home assistant settings under devices? I did try that before and disabled the devices but that did not help before. 
Currently I'm only running your component and it works, did not try to re-enable ecovacs since than, because I'm afraid my system will break down again.

**Comment by And3rsL** [comment]
yes is mandatory to filter only robot you want

for multiple robots just duplicate - platform: deebot etcc.. etc..

**Comment by h4nc** [comment]
> I added back the deebot component and now after trying to restart my system seems to be broken again. Even rebooting hassio doesn't work. 

I faced this issue again with the last major updates (updating to 0.106 and 0.107, see [this thread](https://community.home-assistant.io/t/ha-doesnt-doesnt-start-after-updating-to-0-105-0-106-0-107/179581))

Before updating to 0.108 I ran the add-on "[Check Home Assistant configuration](https://github.com/home-assistant/hassio-addons/tree/master/check_config)" and got an error (see error log below). 
So I commented out the component and ran the check add-on again without an error. After that I ran the update without issues. Of course I can't tell what would have happened if I did the update without commenting it out.

**Comment by h4nc** [comment]
This is the error. Hope that helps to find the issue. (please let me know if I missed to remove some sensible data)


```
INFO:homeassistant.util.package:Attempting install of deebotozmo==1.2.8
ERROR:homeassistant.util.package:Unable to install package deebotozmo==1.2.8: ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/local/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 328, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 328, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 318, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 287, in unpack_url
    hashes=hashes,
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 159, in unpack_http_url
    link, downloader, temp_dir.path, hashes
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/network/utils.py", line 39, in response_chunks
    decode_content=False,
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
Failed config
  General Errors: 
    - Platform error vacuum.deebot - Requirements for deebot not found: ['deebotozmo==1.2.8'].

Successful config (partial)
```
