### ISSUE TITLE
Set Water Level not working

### ISSUE THREAD

**Issue by StefanoGiu** [And3rsL/Deebot-for-hassio#30]
**Describe the bug**
set_water command is not working
Detected I/O inside the event loop. This is causing stability issues. Please report issue

**Configuration.yaml (Remember to delete your credentials)**
```
vacuum:
  - platform: deebot
    username: -----
    password: ---
    country: it
    continent: eu
    deviceid: ------
```

**Screenshots**
not applicable

**System Informations:**
 - Device: Deebot ozmo 920
 - Home Assistant Version: 0.110.4.
 - Hardware: PC
 - Home Assistant Installation: Windows

**Additional context**
Lovelace command:

                        tap_action:
                          action: call-service
                          service: vacuum.send_command
                          service_data:
                            command: set_water
                            entity_id: vacuum.aspirapolvere
                            params:
                              amount: low

**Logs**
2020-06-12 16:06:17 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1837684637360] Detected I/O inside the event loop. This is causing stability issues. Please report issue
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\homeassistant\components\websocket_api\commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "C:\Python38\lib\site-packages\homeassistant\core.py", line 1253, in async_call
    task.result()
  File "C:\Python38\lib\site-packages\homeassistant\core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity_component.py", line 212, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "C:\Python38\lib\site-packages\homeassistant\helpers\service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "C:\Python38\lib\site-packages\homeassistant\helpers\entity.py", line 597, in async_request_call
    await coro
  File "C:\Python38\lib\site-packages\homeassistant\helpers\service.py", line 485, in _handle_entity_call
    await result
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\custom_components\deebot\vacuum.py", line 233, in async_send_command
    return await self.hass.async_add_executor_job(self.device.SetWaterLevel(params['amount']))
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 578, in SetWaterLevel
    self.exc_command('setWaterInfo', {'amount': WATER_LEVEL_TO_ECOVACS[amount], 'enable': 0})
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 582, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 586, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\ecovacsiotmq.py", line 115, in send_command
    self._handle_ctl_api(action, self.CallIOTApi(self.jsonRequestHeader(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\ecovacsiotmq.py", line 178, in CallIOTApi
    with requests.post(url, headers=headers, json=params, timeout=20, verify=verify_ssl) as response:
  File "C:\Python38\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python38\lib\http\client.py", line 1241, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\urllib3\connection.py", line 199, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "C:\Python38\lib\site-packages\homeassistant\util\async_.py", line 120, in protected_loop_func
    check_loop()
  File "C:\Python38\lib\site-packages\homeassistant\util\async_.py", line 91, in check_loop
    raise RuntimeError(
RuntimeError: Detected I/O inside the event loop. This is causing stability issues. Please report issue

**Comment by And3rsL** [comment]
fixed in next release
