### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by SmartM-ui** [And3rsL/Deebot-for-hassio#34]
Hi, 
lately I always have this error and the icon marked in yellow does not change color returning to the previous state. 

Logger: homeassistant.components.script
Source: custom_components/deebot/vacuum.py:222
Integration: Script ([documentation](https://www.home-assistant.io/integrations/script), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+script%22))
First occurred: 15:00:32 (1 occurrences)
Last logged: 15:00:32

Pulisci zona: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object is not callable

Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step self, f"_async_{cv.determine_script_action(self._action)}_step" File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 656, in _async_call_service_step *self._prep_call_service_step(), blocking=True, context=self._context File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in async_call task.result() File "/usr/src/homeassistant/homeassistant/core.py", line 1295, in _execute_service await handler.func(service_call) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service self._platforms.values(), func, call, required_features File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call future.result() # pop exception if have File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call await coro File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call await result File "/config/custom_components/deebot/vacuum.py", line 222, in async_send_command return await self.hass.async_add_executor_job(self.device.SpotArea(params['rooms'], params['cleanings'])) File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) TypeError: 'NoneType' object is not callable

**Comment by And3rsL** [comment]
Can you describe how script 'Pulisci zona' is ?

**Comment by SmartM-ui** [comment]
> 
> 
> Can you describe how script 'Pulisci zona' is ?

Hi Andrea, how's it going? 
Thanks again for the excellent work of the map in real time :-)

Here is the required script:

vacuum_clean_zone:
  alias: Pulisci zona
  sequence:
  - service: vacuum.send_command
    data_template:
      command: spot_area 
      entity_id: vacuum.cenerentola 
      params:
        rooms: >-
              {%- set x = "" %}
              {% if is_state('input_boolean.deebot_cucina', 'on') %}
                {% set x = x + "4," %}
              {% endif %}
              {% if is_state('input_boolean.deebot_salone', 'on') %}
                {% set x = x + "a," %}
              {% endif %}
              {% if is_state('input_boolean.deebot_ingresso', 'on') %}
                {% set x = x + "2," %}
              {% endif %}
              {% if is_state('input_boolean.deebot_bagno1p','on') %}
                {% set x = x + "3," %}
              {% endif %}  
              {% if is_state('input_boolean.deebot_camerasergio','on') %}
                {% set x = x + "7," %}
              {% endif %}
              {% if is_state('input_boolean.deebot_bagno2p', 'on') %}
                {% set x = x + "5," %}
              {% endif %}  
              {% if is_state('input_boolean.deebot_corridoio', 'on') %}
                {% set x = x + "8," %}
              {% endif %}
              {% if is_state('input_boolean.deebot_cameramatrimoniale', 'on') %}
                {% set x = x + "13," %}
              {% endif %}
              {% if is_state('input_boolean.deebot_studio', 'on') %}
                {% set x = x + "0," %}
              {% endif %}
                {{x[:-1]}}
        cleanings: >-
              {%- if is_state('input_boolean.deebot_times', 'on') -%}2{%- else
              -%}1{%- endif -%}
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_cucina
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_salone
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_ingresso
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_bagno1p
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_camerasergio
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_bagno2p
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_corridoio
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_cameramatrimoniale
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_studio
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.deebot_times

**Comment by SmartM-ui** [comment]
Hi Andrea, 
with your latest update you have solved the annoying problem! 

THANK YOU :-)
