### ISSUE TITLE
766 occurrences of  Uncaught thread exception

### ISSUE THREAD

**Issue by bannhead** [And3rsL/Deebot-for-hassio#38]
Hi,
I installed your repo a few days ago. Today I notice the following error in log:

```
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:313
First occurred: 9:27:08 (707 occurrences)
Last logged: 13:22:30

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 492, in refresh_liveMap
    self.live_map = self.__map.GetBase64Map()
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/map.py", line 157, in GetBase64Map
    x = (int(cord[0])/pixelWidth)+offset
ValueError: invalid literal for int() with base 10: ''
```

**Configuration.yaml**
```
vacuum:
- platform: deebot
  username: !secret ecovacs_usr
  password: !secret ecovacs_psw
  country: it
  continent: eu
  deviceid: !secret ecovacs_id
  # Optional
  live_map: True
  show_color_rooms: True
  livemappath: 'www/live_map.png'
```

**System Informations:**
 - Device: Deebot ozmo T8 AIVI
 - Home Assistant Version: 0.114.0
 - Hardware: Raspberry pi 3 model B+
 - Home Assistant Installation: HassOS 4.12

**Additional context**
Today I switched show_color_rooms to true, but I don't know if it is related.

[home-assistant.log](https://github.com/And3rsL/Deebot-for-hassio/files/5074375/home-assistant.log)

**Comment by And3rsL** [comment]
Yes, is related to show_color_rooms, disable it

its currently buggy, i will look into it :)

**Comment by And3rsL** [comment]
No more errors
