### ISSUE TITLE
call to iotdevmanager failed with ReadTimeout

### ISSUE THREAD

**Issue by DaaXDooR** [And3rsL/Deebot-for-hassio#4]
Home Assistent 0.105.5

call to iotdevmanager failed with ReadTimeout
10:59 /usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py (WARNING)
WARNING (mqtt_schedule_thread) [deebotozmo] call to iotdevmanager failed with ReadTimeout

**Comment by langerhans** [comment]
Seeing the same issue here on 0.106.5. The component fails to setup and blocks startup of HA and later keeps repeating the same entries in the log:

```
2020-03-07 18:43:30 INFO (MainThread) [homeassistant.components.vacuum] Setting up vacuum.deebot
2020-03-07 18:43:30 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 2.6 seconds.
2020-03-07 18:44:00 WARNING (MainThread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2020-03-07 18:44:30 WARNING (mqtt_schedule_thread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2020-03-07 18:44:30 WARNING (MainThread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2020-03-07 18:45:00 WARNING (mqtt_schedule_thread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
2020-03-07 18:45:00 WARNING (MainThread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}```

**Comment by ronytomen** [comment]
Same, seems the setup is not async and blocking.

```
Mar 12 08:58:31 hass[17794]: 2020-03-12 08:58:31 WARNING (mqtt_schedule_thread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Mar 12 08:58:31 hass[17794]: 2020-03-12 08:58:31 WARNING (MainThread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Mar 12 08:59:01 hass[17794]: 2020-03-12 08:59:01 WARNING (mqtt_schedule_thread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Mar 12 08:59:02 hass[17794]: 2020-03-12 08:59:02 WARNING (MainThread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Mar 12 08:59:32 hass[17794]: 2020-03-12 08:59:32 WARNING (mqtt_schedule_thread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Mar 12 08:59:32 hass[17794]: 2020-03-12 08:59:32 WARNING (mqtt_schedule_thread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
Mar 12 08:59:32 hass[17794]: 2020-03-12 08:59:32 WARNING (MainThread) [deebotozmo] call to iotdevmanager failed with {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```

**Comment by And3rsL** [comment]
Can you try if its still blocking or not? im new to python dev and im trying to understand how async calls work :D

**Comment by hellofaduck** [comment]
Same problem here, and i think maybe problem not in servers or not only in servers...
1. What setting i need to use in Russia? i use country - RU and continent(??) - EU is that right???
2. through my pi-hole dns server i see that my android ecovacs software connecting to 
- mq-ww.ecouser.net - 47.254.143.26
- msg-ww.ecouser.net - 47.91.67.63
- bigdata-europe.ecovacs.com - 47.91.65.122
- gl-ru-api.ecovacs.com - 47.91.65.136
- portal-ww.ecouser.net - 47.91.67.63
BUT homeassistant trying to connect to:
- portal-eu.ecouser.net - 47.91.67.63
- mq-eu.ecouser.net - 47.254.143.26
- eco-ru-api.ecovacs.com - not exist
so.. i desided to help HA to find right way and add to hosts file that eco-ru-api.ecovacs.com is 47.91.65.136 like gl-ru-api.ecovacs.com.
And what i have now - Home Assistant _now_ starting normal, but i have new error :( in home-assistant.log:

> 2020-04-26 10:45:06 ERROR (MainThread) [deebotozmo] call to user/login failed with {'code': '0002', 'time': 1587897906225}
2020-04-26 10:45:06 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up deebot platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/deebot/vacuum.py", line 93, in async_setup_platform
    config.get(CONF_CONTINENT),
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 202, in __init__
    ('password', self.encrypt(password_hash)))
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 245, in __call_main_api
    json['code'], json['msg'], function, args))
KeyError: 'msg'

I checked all my credentials twice, login and logout in ecovacs app, all normal. Checked ID of my ecovacs its all correct. I have ecovacs DE55 not OSMO series but i think its doesnt matter they use one app and i belive 1 API, maybe my deebot dont recognize some additional command.
What you think, how i can debug this and what my next step?
P.S. Thank for this great addon! I hope we can kickstart it :))

**Comment by And3rsL** [comment]
can you share your config? remember to asterisks username and password

**Comment by h4nc** [comment]
> Seeing the same issue here on 0.106.5. The component fails to setup and blocks startup of HA and later keeps repeating the same entries in the log.

Looks like I have/had the same issue [here](https://github.com/And3rsL/Deebot-for-hassio/issues/3#issuecomment-584297715). Gave me a [hard time](https://github.com/And3rsL/Deebot-for-hassio/issues/3#issuecomment-584385560), because the only solution I found was to restore my system. 

Currently on 108.9 I don't see the "iotdevmanager" warning but my log file is full of this:  

`WARNING (MainThread) [homeassistant.helpers.entity] Update of vacuum.deebot is taking over 10 seconds`

**Comment by cagnulein** [comment]
<pre>2020-05-06 06:12:59 INFO (MainThread) [hacs.data] Restore started
2020-05-06 06:13:01 INFO (MainThread) [hacs.data] Restore done
2020-05-06 06:13:01 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2020-05-06 06:13:12 WARNING (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-06 06:13:33 WARNING (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-06 06:13:53 WARNING (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-06 06:14:13 WARNING (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-06 06:14:34 WARNING (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-06 06:14:54 WARNING (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-06 06:15:14 WARNING (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-06 06:15:34 WARNING (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-06 06:15:55 WARNING (SyncWorker_0) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-06 06:15:55 ERROR (MainThread) [homeassistant.components.vacuum] deebot: Error on device update!</pre>

config
<pre>vacuum:
  - platform: deebot
    username: xxxx@gmail.com
    password: xxxx
    country: IT
    continent: EU
    deviceid: e20012xxxx007xx92</pre>

**Comment by And3rsL** [comment]
Should work now ! Can you try?

**Comment by cagnulein** [comment]
> Should work now ! Can you try?

my deebot is in assistance i think it will return the next week (broken wheel). I will test for sure. Thanks

**Comment by cagnulein** [comment]
> Should work now ! Can you try?

same thing
<pre>
2020-05-22 11:52:37 WARNING (SyncWorker_4) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-22 11:52:57 WARNING (SyncWorker_4) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-22 11:53:17 WARNING (SyncWorker_4) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-22 11:53:38 WARNING (SyncWorker_4) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-22 11:53:58 WARNING (SyncWorker_4) [deebotozmo] call to iotdevmanager failed with ReadTimeout
2020-05-22 11:54:19 WARNING (SyncWorker_4) [deebotozmo] call to iotdevmanager failed with ReadTimeout
</pre>

my actual config:
<pre>
vacuum:
  - platform: deebot
    username: fsdfd@gmail.com
    password: xxxxx
    country: IT
    continent: EU
    deviceid: E000xxxxxxxxxxx
  - platform: deebot
    username: fdfdfd@gmail.com
    password: xxxxxx
    country: IT
    continent: EU
    deviceid: e20xxxxxxxxx
</pre>

**Comment by And3rsL** [comment]
You didnt update the componen

**Comment by cagnulein** [comment]
> You didnt update the componen? It shouldnt work with this config

you were right sorry, anyway i upgraded it and now i have these errors:

<pre>
2020-05-22 16:07:06 ERROR (SyncWorker_3) [deebotozmo] call to GetDeviceList failed with {'todo': 'result', 'result': 'fail', 'errno': 1004, 'error': 'auth error'}
2020-05-22 16:07:08 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up deebot platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/vacuum.py", line 101, in setup_platform
    devices = ecovacs_api.devices()
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 215, in devices
    return self.SetIOTMQDevices(self.getdevices())
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 182, in getdevices
    }, verify_ssl=self.verify_ssl)['devices']
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 161, in __call_portal_api
    "failure {} ({}) for call {} and parameters {}".format(json['error'], json['errno'], function, params))
RuntimeError: failure auth error (1004) for call GetDeviceList and parameters {'todo': 'GetDeviceList', 'userid': 'xxxx', 'auth': {'with': 'users', 'userid': 'xxxx', 'realm': 'ecouser.net', 'token': 'xxxx', 'resource': 'xxx'}}
2020-05-22 16:07:43 ERROR (MainThread) [custom_components.deebot.vacuum] STATE not supported: None
20-05-22 16:07:43 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 551, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 324, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/deebot/vacuum.py", line 250, in device_state_attributes
    data['robot_status'] = STATE_CODE_TO_STATE[self.device.vacuum_status]
KeyError: None
2020-05-22 16:08:03 ERROR (MainThread) [custom_components.deebot.vacuum] STATE not supported: None
2020-05-22 16:08:03 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 551, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 324, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/deebot/vacuum.py", line 250, in device_state_attributes
    data['robot_status'] = STATE_CODE_TO_STATE[self.device.vacuum_status]
KeyError: None
</pre>

**Comment by cagnulein** [comment]
any ideas?

**Comment by And3rsL** [comment]
its a login problem.. can you confirm u are using Ecovacs HOME app?

**Comment by cagnulein** [comment]
> its a login problem.. can you confirm u are using Ecovacs HOME app?

yes of course. Username and password are also both correct

**Comment by cagnulein** [comment]
installed 1.9.3

<pre>
2020-06-04 15:28:59 ERROR (SyncWorker_1) [deebotozmo] call to GetDeviceList failed with {'todo': 'result', 'result': 'fail', 'errno': 1004, 'error': 'auth error'}
2020-06-04 15:28:59 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up deebot platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/vacuum.py", line 105, in setup_platform
    devices = ecovacs_api.devices()
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 196, in devices
    return self.SetIOTMQDevices(self.getdevices())
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 173, in getdevices
    }, verify_ssl=self.verify_ssl)['devices']
  File "/usr/local/lib/python3.7/site-packages/deebotozmo/__init__.py", line 152, in __call_portal_api
    "failure {} ({}) for call {} and parameters {}".format(json['error'], json['errno'], function, params))
</pre>

I know it's a auth issue but the user and password are fine. I've also insert the same user & password on the app (logout and login) and it works. How can i try the API directly?

**Comment by cagnulein** [comment]
https://github.com/And3rsL/Deebotozmo/issues/7
