### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by StefanoGiu** [And3rsL/Deebot-for-hassio#41]
**Describe the bug**
I get an error in the log

**System Informations:**
 - Device: Deebot ozmo 920
 - Home Assistant Version: 0.114.4
 - Hardware: PC
 - Home Assistant Installation: Windows

**Logs**
2020-09-10 09:49:15 ERROR (schedule_thread_statuses) [root] Uncaught thread exception
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 475, in refresh_statuses
    self.exc_command('getCleanInfo')
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 582, in exc_command
    self.send_command(VacBotCommand(action, params))
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\__init__.py", line 586, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\ecovacsiotmq.py", line 115, in send_command
    self._handle_ctl_api(action, self.CallIOTApi(self.jsonRequestHeader(action, recipient) ,verify_ssl=self.verify_ssl ))
  File "C:\Users\stefa\AppData\Roaming\.homeassistant\deps\Python38\site-packages\deebotozmo\ecovacsiotmq.py", line 216, in _handle_ctl_api
    if 'resp' in message:
TypeError: argument of type 'NoneType' is not iterable

**Comment by StefanoGiu** [comment]
Can you check if this is a valid fix?

`    def _handle_ctl_api(self, action, message):
        if not message == {}:
            if(action.name.lower() == 'getcleanlogs'):
                resp = self._ctl_to_dict_api(action, message)
            else:
                if message is not None:
                   if 'resp' in message:
                       resp = self._ctl_to_dict_api(action, message['resp'])
                   else:
                       return
                else:
                   return`

**Comment by magicdude4eva** [comment]
Having the same issue via Home Assistant (0.116.4) - as far as I understand with the Hassio image I would not have access to "/usr/local/lib/python3.8/site-packages/deebotozmo/" - or am I missing something?
