### ISSUE TITLE
Cannot configure "Max Retries Exceeded"

### ISSUE THREAD

**Issue by deputyd0ng** [And3rsL/Deebot-for-hassio#62]
**Describe the bug**
Cannot configure integration, installed from HACS

**Configuration.yaml (Remember to delete your credentials)**
```
vacuum:
  - platform: deebot
    username: ****
    password: ****
    country: usa
    continent: na
    deviceid: E000072901860890****
```

**Screenshots**

**System Informations:**
 - Device: Deebot 907
 - Home Assistant Version: 2020.12.0
 - Hardware: Pi 4
 - Home Assistant Installation: Home Assistant OS

--

**Additional context**

**Logs**
`Logger: homeassistant.setup
Source: custom_components/deebot/__init__.py:71
First occurred: 6:01:54 PM (1 occurrences)
Last logged: 6:01:54 PM

Error during setup of component deebot
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f849bb1c0>: Failed to establish a new connection: [Errno -2] Name does not resolve

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='eco-usa-api.ecovacs.com', port=443): Max retries exceeded with url: /v1/private/usa/en/DVOF5S2Z/i_eco_e/1.3.5/c_googleplay/1/user/login?account=19sp9ie8TdZanwfoPjbT2JrDKE4%2FLb%2Bw1Ruo1FyT%2F69u4uqJjqoLR%2FbqsPJQFwlqzwqvknApGfwJY%2F8ph7%2BrrrMzW4rwU6NE9DHw1794wWUck29XopglzJaw3N1Qs04KnbqvsNiducPoGn3LbvzFj50Gm8F4xTrdom23NgxA8ig%3D&password=r%2FaSS6qjpkYgv1WEw7ONmhKY%2BO%2F1q%2FTKKgt1rojNRY7mVnNWuk7TuSJxaHXXFbCUSznMSUn5MXnZLJdMbiTpPrjkQCR1MPfqttYvv5LsVjWf2B2oTPtGxKbr4aQ%2FhgfveuFt9jJD1gO6wAxZ8nGmG6PDGhIjpzhYKcXtX2IiVNc%3D&requestId=07781721645fd4a806674c448a47ff84&authTimespan=1608073311826&authTimeZone=GMT-8&authAppkey=eJUWrzRv34qFSaYk&authSign=ca69614154a426ea4b9b66738e34a81f (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f849bb1c0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/__init__.py", line 55, in setup
    HUB = DeebotHub(config[DOMAIN])
  File "/config/custom_components/deebot/__init__.py", line 71, in __init__
    self.ecovacs_api = EcoVacsAPI(
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 52, in __init__
    login_info = self.__call_main_api('user/login',
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 91, in __call_main_api
    api_response = requests.get(url, self.__sign(params), verify=self.verify_ssl)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='eco-usa-api.ecovacs.com', port=443): Max retries exceeded with url: /v1/private/usa/en/DVOF5S2Z/i_eco_e/1.3.5/c_googleplay/1/user/login?account=19sp9ie8TdZanwfoPjbT2JrDKE4%2FLb%2Bw1Ruo1FyT%2F69u4uqJjqoLR%2FbqsPJQFwlqzwqvknApGfwJY%2F8ph7%2BrrrMzW4rwU6NE9DHw1794wWUck29XopglzJaw3N1Qs04KnbqvsNiducPoGn3LbvzFj50Gm8F4xTrdom23NgxA8ig%3D&password=r%2FaSS6qjpkYgv1WEw7ONmhKY%2BO%2F1q%2FTKKgt1rojNRY7mVnNWuk7TuSJxaHXXFbCUSznMSUn5MXnZLJdMbiTpPrjkQCR1MPfqttYvv5LsVjWf2B2oTPtGxKbr4aQ%2FhgfveuFt9jJD1gO6wAxZ8nGmG6PDGhIjpzhYKcXtX2IiVNc%3D&requestId=07781721645fd4a806674c448a47ff84&authTimespan=1608073311826&authTimeZone=GMT-8&authAppkey=eJUWrzRv34qFSaYk&authSign=ca69614154a426ea4b9b66738e34a81f (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f849bb1c0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))`

**Comment by deputyd0ng** [comment]
Stupid me, I had "usa" instead of "us" in for country.

HA now reboots without telling me the config failed, but I also have no new entities/ deebot does not show up.

**Comment by deputyd0ng** [comment]
update:  entities have appeared, displays not data, does not seem to have ever "come online"

**Comment by edenhaus** [comment]
Can you please update your issue and post your new logs and config otherwise it is hard to help.
Please also format your logs as code, it will help reading it.

**Comment by edenhaus** [comment]
Closing it as it is stale
