### ISSUE TITLE
Error loading my ecovacs entity

### ISSUE THREAD

**Issue by WelpeLP** [And3rsL/Deebot-for-hassio#63]
**Describe the bug**
I wanted to connect my Ecovacs bot to Home Assistant, but it fails with the later stated error.

**Configuration.yaml (Remember to delete your credentials)**
```
vacuum:
 deebot:
  username: MYMAIL@gmail.com
  password: MYPASSWD
  country: DE
  continent: EU
  deviceid:
    - E0000000000000MYID
  # Optional
  live_map: True                    
  show_color_rooms: True
  livemappath: 'www/' 

camera:
  - platform: generic
    name: Deebot_live_map
    still_image_url: "http://localhost:8123/local/live_map.png"
    verify_ssl: false
```

**System Informations:**
 - Device: Ozmo T8+
 - Home Assistant Version: Core 2020.12.1
 - Hardware: Raspberry Pi 3B
 - Home Assistant Installation: Raspbian
- HACS Version: 1.9.0

**Logs**
Complete (and only) error message:
```
2020-12-22 07:14:19 ERROR (MainThread) [homeassistant.setup] Error during setup of component deebot

Traceback (most recent call last):

File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/setup.py", line 213, in _async_setup_component

result = await task

File "/usr/local/opt/python-3.9.1/lib/python3.9/concurrent/futures/thread.py", line 52, in run

result = self.fn(*self.args, **self.kwargs)

File "/home/homeassistant/.homeassistant/custom_components/deebot/__init__.py", line 55, in setup

HUB = DeebotHub(config[DOMAIN])

File "/home/homeassistant/.homeassistant/custom_components/deebot/__init__.py", line 99, in __init__

vacbot.connect_and_wait_until_ready()

File "/srv/homeassistant/lib/python3.9/site-packages/deebotozmo/__init__.py", line 267, in connect_and_wait_until_ready

self.iotmq.schedule(30, self.send_ping)

File "/srv/homeassistant/lib/python3.9/site-packages/deebotozmo/ecovacsiotmq.py", line 84, in schedule

if not self.scheduler_thread.isAlive():

AttributeError: 'Thread' object has no attribute 'isAlive'


```

**Comment by edenhaus** [comment]
Can you please try to upgrade to the latest version, which is currently `1.9.7` and confirm that the issue still exists

**Comment by WelpeLP** [comment]
> Can you please try to upgrade to the latest version, which is currently `1.9.7` and confirm that the issue still exists

I installed the newest version, but the issue still persists.

**Comment by edenhaus** [comment]
How did you install Home Assistant? Did you use a support installation method (https://www.home-assistant.io/docs/installation/)?

Can you try to downgrade to python 3.8 and check if the issue still exists? All my HA instances run on python 3.8 with Home Assistant Container

**Comment by And3rsL** [comment]
https://github.com/And3rsL/Deebotozmo/pull/20#issue-547612552

Should fix the problem, please wait for the next release
