### ISSUE TITLE
Uncaught thread exception

### ISSUE THREAD

**Issue by K-RAD** [And3rsL/Deebot-for-hassio#64]
Keep getting this error

```
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:312
First occurred: 6:50:36 PM (1 occurrences)
Last logged: 6:50:36 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 526, in refresh_liveMap
    self.live_map = self.__map.GetBase64Map()
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/map.py", line 158, in GetBase64Map
    x = (int(cord[0])/pixelWidth)+offset
ValueError: invalid literal for int() with base 10: ''
```

**Comment by LuckyTriple7** [comment]
Same Issue here:
OZMO T8 AIVI

`Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 526, in refresh_liveMap
    self.live_map = self.__map.GetBase64Map()
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/map.py", line 158, in GetBase64Map
    x = (int(cord[0])/pixelWidth)+offset
ValueError: invalid literal for int() with base 10: ''`

**Comment by gmkrib** [comment]
Same Issue here:
OZMO T8

2020-12-26 16:41:19 ERROR (schedule_thread_livemap) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 526, in refresh_liveMap
self.live_map = self.__map.GetBase64Map()
File "/usr/local/lib/python3.8/site-packages/deebotozmo/map.py", line 158, in GetBase64Map
x = (int(cord[0])/pixelWidth)+offset
ValueError: invalid literal for int() with base 10: ''

**Comment by edenhaus** [comment]
Since when the issue exists? Was there a firmware update of the deebot or did you change something on the map?

**Comment by gmkrib** [comment]
I only started with the first implementation, so I can't say anything about a change, but my current firmware version is: 1.6.3

**Comment by edenhaus** [comment]
@gmkrib Can you try to debug it? To find out, which data is coming back from the vacuum

Unfortunately Andrea and I have only the 950 and therefore it's hard for us to debug this. See #35 

P.S. Feel free to sponsor me a T8+ :stuck_out_tongue_winking_eye:

**Comment by gmkrib** [comment]
Yes, I will help you to debug it, but how will you do it? I need a little guidance there. i can only recommend you the T8, it does not have to be a T8+ ;)

**Comment by edenhaus** [comment]
No you debug your vacuum and then post here the information you found. I can't debug you vacuum remotely.

The best would be to checkout the source code of the lib and then run the code in the Debugger. Set a break point at the line, where the exception is thrown and see whats inside the variable `cord`.

@gmkrib Marking the last teo post as off topic as the are irrelevant for the issue.

**Comment by gmkrib** [comment]
I would really like to do this but please explain to me exactly what I need to do and how, as I have no experience with Pyton. Which program is necessary for this and please the individual steps as accurately as possible.

p.s. I have experience with programming and debugging but none with Pyton.

**Comment by edenhaus** [comment]
> I would really like to do this but please explain to me exactly what I need to do and how, as I have no experience with Pyton. Which program is necessary for this and please the individual steps as accurately as possible.

Sorry but there exist many tools to debug python. So choose one. I use pycharm (payed) and vscode. Below two links to some tutorials:

- https://code.visualstudio.com/docs/python/debugging
- https://www.jetbrains.com/help/pycharm/debugging-your-first-python-application.html


When you are familiar with debugging, then check out the library code (The problem is happening there).
Afterwards create a python file, where you setup your vacuum.
At the end call the method `refresh_liveMap` and debug whats happening there
https://github.com/And3rsL/Deebotozmo/blob/6ad38ba992ce1372d1c4d6fc53add6270cd8018b/deebotozmo/__init__.py#L547

I will also transfer this issue ti the lib.

**Comment by gmkrib** [comment]
I have downloaded and executed the code but I can't get to the right place. Because in the map.py (for room in self.rooms:) the rooms variable is empty. Any idea why it does not load the rooms or how I push them?

I run this code (live_map_enabled and show_rooms_color are enabled)
api = deebotozmo.EcoVacsAPI(config['device_id'], config['email'], config['password_hash'], config['country'], config['continent'])
my_vac = api.devices()[0]
vacbot = deebotozmo.VacBot(api.uid, api.REALM, api.resource, api.user_access_token, my_vac, 'EU', True, True, True)
vacbot.connect_and_wait_until_ready()
vacbot.refresh_liveMap()

**Comment by LuckyTriple7** [comment]
An attempt is made to update the map when the robot is idle. Could it be that this is the problem?
I don't think it is necessary to update the map when the robot is idle.
