### ISSUE TITLE
Time out issue when I configure 2 deebot

### ISSUE THREAD

**Issue by DJlee68-HA** [And3rsL/Deebot-for-Hassio#97]
**Describe the bug**
I have an issue when I configure 2 ids in the configuration.yaml
With one (id or id2), no problem, if i put the 2 ids, I have an error.

**Configuration.yaml (Remember to delete your credentials)**
```
deebot:
  username: !secret ecovacs_login
  password: !secret ecovacs_password
  country: FR
  continent: EU
  deviceid:
    - !secret ecovacs_sn
    - !secret ecovacs_sn2
```

**System Informations:**
I have 2 ecovacs Ozmo 920

**Logs**
```
Logger: homeassistant.setup
Source: custom_components/deebot/__init__.py:79
First occurred: 18:48:53 (1 occurrences)
Last logged: 18:48:53

Error during setup of component deebot
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0xaeab97d8>, 'Connection to portal-eu.ecouser.net timed out. (connect timeout=60)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='portal-eu.ecouser.net', port=443): Max retries exceeded with url: /api/users/user.do (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xaeab97d8>, 'Connection to portal-eu.ecouser.net timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/__init__.py", line 55, in setup
    HUB = DeebotHub(config[DOMAIN])
  File "/config/custom_components/deebot/__init__.py", line 79, in __init__
    devices = self.ecovacs_api.devices()
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 287, in devices
    return self.SetJSONDevices(self.getdevices())
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 240, in getdevices
    return  self.__call_portal_api(self.USERSAPI,'GetDeviceList', {
  File "/usr/local/lib/python3.8/site-packages/deebotozmo/__init__.py", line 192, in __call_portal_api
    response = requests.post(url, json=params, timeout=60, verify=verify_ssl)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='portal-eu.ecouser.net', port=443): Max retries exceeded with url: /api/users/user.do (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xaeab97d8>, 'Connection to portal-eu.ecouser.net timed out. (connect timeout=60)'))
```

Thank you

**Comment by edenhaus** [comment]
We released today a new version with a lot of refactoring. Now the configuration is done over the UI, therefore I will close this issue as it is obsolete. If you still have problems with the new version please open a new issue
